name: "ModTest: ${workspace}"

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  modtest:
    uses: HappyPathway/centralized-actions/.github/workflows/modtest.yml@main
    with:
      workspace: ${workspace}
      workspace_repo: ${workspace_repo}
      workspace_branch: ${workspace_branch}
      repo_clone_type: ${repo_clone_type}
      mod_source: ${mod_source}

      github_server: $${{vars.GH_SERVER}}
      github_org:  $${{ github.repository_owner }} 
      branch: $${{ github.head_ref }}
      terraform_version: $${{vars.TERRAFORM_VERSION}}
      terraform_api_token_name: $${{ vars.TERRAFORM_API_TOKEN_NAME }}
      terraform_api: $${{vars.TERRAFORM_API}}
       
    secrets:
      TFE_TOKEN: $${{ secrets.TFE_TOKEN }}
      GH_TOKEN: $${{ secrets.GH_TOKEN }}