name: "ModTest: repo-modules"

on:
  pull_request:
    branches:
      - main
    
jobs:
  modtest:
    uses: HappyPathway/centralized-actions/.github/workflows/modtest.yml@main
    with:
      workspace: repo-modules
      workspace_repo: repo-modules
      workspace_branch: main
      repo_clone_type: https
      mod_source: module/tfe

      github_server: ${{vars.GITHUB_SERVER}}
      github_org:  ${{ github.repository_owner }} 
      branch: ${{ github.head_ref }}
      terraform_version: ${{vars.TERRAFORM_VERSION}}
      terraform_api_token_name: ${{ vars.TERRAFORM_API_TOKEN_NAME }}
      terraform_api: ${{vars.TERRAFORM_API}}
       
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}