name: "ModTest: default"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    
jobs:
  modtest:
    if : ${{ github.event_name }} == "pull_request"
    uses: HappyPathway/centralized-actions/.github/workflows/modtest.yml@google
    with:
      workspace: default
      workspace_repo: module-repos
      workspace_branch: main
      repo_clone_type: https
      mod_source: module/tfe

      github_server: ${{vars.GH_SERVER}}
      github_org:  ${{ github.repository_owner }} 
      branch: ${{ github.head_ref }}
      terraform_version: ${{vars.TERRAFORM_VERSION}}
      terraform_api_token_name: ${{ vars.TERRAFORM_API_TOKEN_NAME }}
      terraform_api: ${{vars.TERRAFORM_API}}
       
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
